print(1>2)#KARŞILAŞIRMA İŞLEMİNİN SONUCUNU EKRANA YAZDIRIN (FALSE)
print(2==2)#KARŞILAŞIRMA İŞLEMİNİN SONUCUNU EKRANA YAZDIRIN (TRUE)
print(2<-5)#KARŞILAŞIRMA İŞLEMİNİN SONUCUNU EKRANA YAZDIRIN (FALSE)